name = "tryAtEachStep"
defaultTargets = ["tryAtEachStep", "tryAtEachStepInDirectory"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[lean_exe]]
name = "tryAtEachStep"
supportInterpreter = true

[[lean_exe]]
name = "tryAtEachStepInDirectory"
supportInterpreter = true

[[lean_lib]]
name = "TryAtEachStepTest"
globs = ["TryAtEachStepTest.+"]
leanOptions = {linter.missingDocs = false}

